pub mod biome;
pub mod query;
pub mod terrain;
mod geometry_transaction;
pub mod hydrology;
pub mod corridor;
pub mod accents;
pub mod validation;
pub mod plateau;
pub mod alluvial_fan;
pub mod basin;
pub mod volcanic_lake;
pub mod static_water;

pub use biome::{GeoCell, SurfaceKind};
pub use plateau::PlateauGeometry;
pub use alluvial_fan::FanGeometry;
pub use basin::BasinGeometry;
pub use volcanic_lake::VolcanicLakeGeometry;
pub use query::{explain_failure, sample_cell, validate_footprint, FootprintQuery, LandUseKind, TerrainFailure, TerrainQueryResult};
pub use terrain::{is_static_water_profile, water_source_poi_count, BranchRidge, GenesisOverrides, TerrainFeature, TerrainFeatureKind, TerrainMap, TerrainSubFeature, TerrainSubFeatureKind, TERRAIN_GENERATOR_VERSION, TERRAIN_PROFILE_ALLUVIAL_FAN, TERRAIN_PROFILE_BASIN_OASIS, TERRAIN_PROFILE_FLAT_BASELINE, TERRAIN_PROFILE_GRASSLAND_PLAIN, TERRAIN_PROFILE_HILLSIDE_WOODLAND, TERRAIN_PROFILE_VOLCANIC_LAKE, TERRAIN_PROFILE_MOUNTAIN_PASS, TERRAIN_PROFILE_PLATEAU, TERRAIN_PROFILE_RANDOM, TERRAIN_PROFILE_RIVER_VALLEY};
pub use hydrology::{MeanderWindow, RiverCenterline};
pub use accents::{AccentKind, TerrainAccent, ACCENT_RNG_SALT};
